
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http: !include http.yaml
mqtt: !include mqtt.yaml
telegram_bot: !include telegram_bot.yaml
notify: !include notify.yaml

