FROM linuxserver/domoticz:latest


# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"
ENV TZ=Europe/Paris


RUN \
 echo "**** install runtime packages ****" && \
 apt-get update && \
 apt-get install -y --no-install-recommends --force-yes \
	gcc \
	python3-dev  \
	wiringpi


RUN \
 pip3 install rpi.GPIO && \
 usermod -aG gpio pi


